apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-cloud-operator
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    chart: terraform-cloud-operator
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 2.0.0-beta8
    helm:
      releaseName: tfc
  destination:
    server: "https://kubernetes.default.svc"
    namespace: terraform-cloud-operator