---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: product
  annotations:
    kubernetes.io/service-account.name: "product"
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "database:5432"
        consul.hashicorp.com/transparent-proxy-exclude-outbound-ports: "8200"

        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "products"
        vault.hashicorp.com/namespace: "admin"
        vault.hashicorp.com/agent-inject-secret-conf.json: "hashicups/database/creds/products"
        vault.hashicorp.com/agent-inject-template-conf.json: |
          {
            "bind_address": ":9090",
            "metrics_address": ":9103",
            {{ with secret "hashicups/database/creds/products" -}}
            "db_connection": "host=127.0.0.1 port=5432 user={{ .Data.username }} password={{ .Data.password }} dbname=products sslmode=disable"
            {{- end }}
          }
    spec:
      serviceAccountName: product
      containers:
        - name: product
          image: hashicorpdemoapp/product-api:v0.0.20
          ports:
            - containerPort: 9090
            - containerPort: 9103
          env:
            - name: "CONFIG_FILE"
              value: "/vault/secrets/conf.json"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30