---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-cloud
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-cloud-token
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: terraform-cloud
type: kubernetes.io/service-account-token
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: terraform-cloud
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  method: kubernetes
  mount: kubernetes
  namespace: admin
  kubernetes:
    role: hashicups
    serviceAccount: terraform-cloud
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: terraform-cloud-team-token
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  mount: terraform
  path: creds/hashicups
  destination:
    create: true
    name: terraform-cloud-team-token
    type: Opaque
  vaultAuthRef: terraform-cloud
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: terraform-aws-postgres-variables
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  mount: terraform-cloud-operator/hashicups
  type: kv-v2
  path: terraform-aws-postgres
  destination:
    create: true
    name: terraform-aws-postgres-variables
    type: Opaque
  vaultAuthRef: terraform-cloud