apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-config
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: consul
  source:
    repoURL: 'https://github.com/joatmon08/hashicorp-stack-demoapp.git'
    targetRevision: main
    path: argocd/applications/consul/config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd