apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: promotions
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  method: kubernetes
  mount: kubernetes
  namespace: admin
  kubernetes:
    role: terraform-cloud-operator
    serviceAccount: promotions
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: database-module-variables
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  role: terraform-cloud-operator
  mount: tfc/operator
  destination:
    create: true
    name: tfc-module-variables-database
    type: "Opaque"
  vaultAuthRef: promotions