---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-cloud
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-cloud-token
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: terraform-cloud
type: kubernetes.io/service-account-token
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: terraform-cloud
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  method: kubernetes
  mount: kubernetes
  namespace: admin
  kubernetes:
    role: promotions
    serviceAccount: terraform-cloud
    audiences:
      - vault
# ---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultDynamicSecret
# metadata:
#   name: terraform-cloud
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   mount: terraform
#   path: creds/promotions
#   destination:
#     create: true
#     name: terraform-cloud
#     type: Opaque
#   vaultAuthRef: terraform-cloud
# ---
# apiVersion: secrets.hashicorp.com/v1beta1
# kind: VaultStaticSecret
# metadata:
#   name: database-module-variables
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   role: terraform-cloud-operator
#   mount: tfc/operator
#   path: terraform-aws-postgres
#   destination:
#     create: true
#     name: database-module-variables
#     type: "Opaque"
#   vaultAuthRef: promotions