apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicups
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://github.com/joatmon08/hashicorp-stack-demoapp.git'
    targetRevision: main
    path: application/hashicups
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hashicups