---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: payments-processor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  method: kubernetes
  mount: kubernetes
  namespace: admin
  kubernetes:
    role: payments-processor
    serviceAccount: payments-processor
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payments-processor
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  mount: payments-processor/static
  type: kv-v2
  path: creds
  destination:
    create: true
    name: payments-processor-creds
    type: Opaque
  vaultAuthRef: payments-processor
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: payments-processor
    - kind: Deployment
      name: payments-app