---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments-processor
spec:
  protocol: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-processor
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: payments-processor
  annotations:
    kubernetes.io/service-account.name: "payments-processor"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-processor
  labels:
    app: payments-processor
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31280
  selector:
    app: payments-processor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payments-processor
      app: payments-processor
  template:
    metadata:
      labels:
        service: payments-processor
        app: payments-processor
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      serviceAccountName: payments-processor
      containers:
        - name: payments-processor
          image: rosemarywang/payments-processor
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 8080
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payments-processor-creds
                  key: password